#!/usr/bin/env bash
# This file is modified from CachyOS.

update_lsb_release() {
    sed -i /etc/lsb-release \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=clipsneko|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"ClipsNeko Linux\"|'
}

update_os_release() {
    local os_release="/etc/os-release"
    sed -i "$os_release" \
        -e 's|^NAME=.*$|NAME=\"ClipsNeko Linux\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"ClipsNeko Linux\"|' \
        -e 's|^ID=.*$|ID=clipsneko|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR=\"38;2;255;165;209\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://os.clipsneko.cc/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://wiki.clipsneko.cc/\"|' \
	# -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://bbs.clipsneko.cc/\"|' \
	-e 's|^SUPPORT_URL=.*$||' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/ReSpringClipsNeko/ClipsNeko-bugs\"|' \
        -e 's|^LOGO=.*$|LOGO=clipsneko-logo|'

    # add missing ID_LIKE=
    if ! grep -q "^ID_LIKE=" "$os_release" && grep -q "^ID=" "$os_release"; then
        sed -i "$os_release" -e '/^ID=/a \ID_LIKE=arch'
    fi
}

update_issues() {
    sed -i 's|Arch Linux|ClipsNeko Linux|g' /etc/issue /usr/share/factory/etc/issue
}

case "$1" in
    os-release) update_os_release ;;
    lsb-release) update_lsb_release ;;
    *)
        update_os_release
        update_lsb_release
        update_issues
        ;;
esac
